package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 12:21:40 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Jasen: 31
    Jasen jasen1 = new Jasen(); 
    assertEquals("From: Jasen line: 33", 0, jasen1.getJasenID()); 
    jasen1.rekisteroi(); 
    Jasen jasen2 = new Jasen(); 
    jasen2.rekisteroi(); 
    int n1 = jasen1.getJasenID(); 
    int n2 = jasen2.getJasenID(); 
    assertEquals("From: Jasen line: 39", n2-1, n1); 
  } // Generated by ComTest END
}