package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.30 13:03:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Jasen: 31
    Jasen jasen1 = new Jasen(); 
    assertEquals("From: Jasen line: 33", 0, jasen1.getJasenID()); 
    jasen1.rekisteroi(); 
    Jasen jasen2 = new Jasen(); 
    jasen2.rekisteroi(); 
    int n1 = jasen1.getJasenID(); 
    int n2 = jasen2.getJasenID(); 
    assertEquals("From: Jasen line: 39", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString61 */
  @Test
  public void testToString61() {    // Jasen: 61
    Jasen jasen = new Jasen(); 
    jasen.parse("   1  |  Jouko Jii   | 123445-1212"); 
    assertEquals("From: Jasen line: 64", true, jasen.toString().startsWith("1|Jouko Jii|123445-1212|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse87 */
  @Test
  public void testParse87() {    // Jasen: 87
    Jasen jasen = new Jasen(); 
    jasen.parse("   1  |  Jouko Jii   | 123445-1212"); 
    assertEquals("From: Jasen line: 90", 1, jasen.getJasenID()); 
    assertEquals("From: Jasen line: 91", true, jasen.toString().startsWith("1|Jouko Jii|123445-1212|")); 
    jasen.rekisteroi(); 
    int n = jasen.getJasenID(); 
    jasen.parse(""+(n+10)); 
    jasen.rekisteroi(); 
    assertEquals("From: Jasen line: 97", n+10+1, jasen.getJasenID()); 
  } // Generated by ComTest END
}