package seurarekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import seurarekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.08 12:06:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LainatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta48 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta48() throws SailoException {    // Lainat: 48
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    lainat.lueTiedostosta(); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.lisaa(laina2); 
    lainat.tallenna(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa158 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa158() throws SailoException {    // Lainat: 158
    Lainat lainat = new Lainat(); 
    Laina eka = new Laina(1,1); 
    Laina toka = new Laina(2,2); 
    assertEquals("From: Lainat line: 163", 0, lainat.getLkm()); 
    lainat.lisaa(eka); assertEquals("From: Lainat line: 164", 1, lainat.getLkm()); 
    lainat.lisaa(toka); assertEquals("From: Lainat line: 165", 2, lainat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLainatIterator190 
   * @throws SailoException when error
   */
  @Test
  public void testLainatIterator190() throws SailoException {    // Lainat: 190
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    laina1.rekisteroi(); laina2.rekisteroi(); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    lainat.lisaa(laina1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Laina laina:lainat)
    ids.append(" "+laina.getLainaID()); 
    String tulos = " " + laina1.getLainaID() + " " + laina2.getLainaID() + " " + laina1.getLainaID(); 
    assertEquals("From: Lainat line: 208", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Laina>  i=lainat.iterator(); i.hasNext(); ) {
    Laina laina = i.next(); 
    ids.append(" "+laina.getLainaID()); 
    }
    assertEquals("From: Lainat line: 216", tulos, ids.toString()); 
    Iterator<Laina>  i=lainat.iterator(); 
    assertEquals("From: Lainat line: 219", true, i.next() == laina1); 
    assertEquals("From: Lainat line: 220", true, i.next() == laina2); 
    assertEquals("From: Lainat line: 221", true, i.next() == laina1); 
    try {
    i.next(); 
    fail("Lainat: 223 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi273 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi273() throws SailoException {    // Lainat: 273
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1); laina1.parse("1|1|1"); 
    Laina laina2 = new Laina(2,2); laina2.parse("2|2|2"); 
    Laina laina3 = new Laina(3,3); laina3.parse("3|3|3"); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
  } // Generated by ComTest END
}