package seurarekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import seurarekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.15 21:25:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LainatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta48 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta48() throws SailoException {    // Lainat: 48
    Lainat lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaLaina82 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaLaina82() throws SailoException {    // Lainat: 82
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    lainat.poistaLaina(id1+1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPalautaEnsinLainat103 
   * @throws SailoException when error
   */
  @Test
  public void testPalautaEnsinLainat103() throws SailoException {    // Lainat: 103
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 110", 0, lainat.palautaEnsinLainat(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPalautaEnsin128 
   * @throws SailoException when error
   */
  @Test
  public void testPalautaEnsin128() throws SailoException {    // Lainat: 128
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 135", 1, lainat.palautaEnsin(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista151 
   * @throws SailoException when error
   */
  @Test
  public void testPoista151() throws SailoException {    // Lainat: 151
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 158", 1, lainat.poista(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId174 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId174() throws SailoException {    // Lainat: 174
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 181", 1, lainat.etsiId(id1+1)); 
    assertEquals("From: Lainat line: 182", 2, lainat.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa267 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa267() throws SailoException {    // Lainat: 267
    Lainat lainat = new Lainat(); 
    Laina eka = new Laina(1,1); 
    Laina toka = new Laina(2,2); 
    assertEquals("From: Lainat line: 272", 0, lainat.getLkm()); 
    lainat.lisaa(eka); assertEquals("From: Lainat line: 273", 1, lainat.getLkm()); 
    lainat.lisaa(toka); assertEquals("From: Lainat line: 274", 2, lainat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLainatIterator299 
   * @throws SailoException when error
   */
  @Test
  public void testLainatIterator299() throws SailoException {    // Lainat: 299
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    laina1.rekisteroi(); laina2.rekisteroi(); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    lainat.lisaa(laina1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Laina laina:lainat)
    ids.append(" "+laina.getLainaID()); 
    String tulos = " " + laina1.getLainaID() + " " + laina2.getLainaID() + " " + laina1.getLainaID(); 
    assertEquals("From: Lainat line: 317", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Laina>  i=lainat.iterator(); i.hasNext(); ) {
    Laina laina = i.next(); 
    ids.append(" "+laina.getLainaID()); 
    }
    assertEquals("From: Lainat line: 325", tulos, ids.toString()); 
    Iterator<Laina>  i=lainat.iterator(); 
    assertEquals("From: Lainat line: 328", true, i.next() == laina1); 
    assertEquals("From: Lainat line: 329", true, i.next() == laina2); 
    assertEquals("From: Lainat line: 330", true, i.next() == laina1); 
    try {
    i.next(); 
    fail("Lainat: 332 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}