package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 17:55:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LainaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi43 */
  @Test
  public void testRekisteroi43() {    // Laina: 43
    Laina eka = new Laina(1,2); 
    assertEquals("From: Laina line: 45", 0, eka.getLainaID()); 
    eka.rekisteroi(); 
    Laina toka = new Laina(2,1); 
    toka.rekisteroi(); 
    int n1 = eka.getLainaID(); 
    int n2 = toka.getLainaID(); 
    assertEquals("From: Laina line: 51", n2-1, n1); 
  } // Generated by ComTest END
}