package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.15 20:59:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LainaTest {



  // Generated by ComTest BEGIN
  /** testGetJasenID36 */
  @Test
  public void testGetJasenID36() {    // Laina: 36
    Laina laina1 = new Laina(1,2); 
    assertEquals("From: Laina line: 38", 1, laina1.getJasenID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi50 */
  @Test
  public void testRekisteroi50() {    // Laina: 50
    Laina eka = new Laina(1,2); 
    assertEquals("From: Laina line: 52", 0, eka.getLainaID()); 
    eka.rekisteroi(); 
    Laina toka = new Laina(2,1); 
    toka.rekisteroi(); 
    int n1 = eka.getLainaID(); 
    int n2 = toka.getLainaID(); 
    assertEquals("From: Laina line: 58", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString71 */
  @Test
  public void testToString71() {    // Laina: 71
    Laina laina = new Laina(1,1); 
    laina.parse("   1  | 1 "); 
    assertEquals("From: Laina line: 74", true, laina.toString().startsWith("1|1|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse90 */
  @Test
  public void testParse90() {    // Laina: 90
    Laina laina = new Laina(2,1); 
    laina.parse("   2  |  1  "); 
    assertEquals("From: Laina line: 93", 1, laina.getJasenID()); 
    assertEquals("From: Laina line: 94", true, laina.toString().startsWith("2|1|")); 
    laina.rekisteroi(); 
    int n = laina.getLainaID(); 
    laina.parse(""+(n+15)); 
    laina.rekisteroi(); 
    assertEquals("From: Laina line: 100", n+15+1, laina.getLainaID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetValineID134 */
  @Test
  public void testGetValineID134() {    // Laina: 134
    Laina laina1 = new Laina(1,2); 
    assertEquals("From: Laina line: 136", 2, laina1.getValineID()); 
  } // Generated by ComTest END
}