package seurarekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import seurarekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 21:25:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LainatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta48 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta48() throws SailoException {    // Lainat: 48
    Lainat lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    assertEquals("From: Lainat line: 64", false, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    fbak.delete(); 
    assertEquals("From: Lainat line: 67", false, fbak.delete()); 
    assertEquals("From: Lainat line: 68", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaLaina93 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaLaina93() throws SailoException {    // Lainat: 93
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    lainat.poistaLaina(id1+1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPalautaEnsinLainat114 
   * @throws SailoException when error
   */
  @Test
  public void testPalautaEnsinLainat114() throws SailoException {    // Lainat: 114
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 121", 0, lainat.palautaEnsinLainat(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPalautaEnsin139 
   * @throws SailoException when error
   */
  @Test
  public void testPalautaEnsin139() throws SailoException {    // Lainat: 139
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 146", 1, lainat.palautaEnsin(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista162 
   * @throws SailoException when error
   */
  @Test
  public void testPoista162() throws SailoException {    // Lainat: 162
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 169", 1, lainat.poista(id1+1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId185 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId185() throws SailoException {    // Lainat: 185
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,2), laina2 = new Laina(2,3), laina3 = new Laina(3,1); 
    laina1.rekisteroi(); laina2.rekisteroi(); laina3.rekisteroi(); 
    int id1 = laina1.getLainaID(); 
    lainat.lisaa(laina1); lainat.lisaa(laina2); lainat.lisaa(laina3); 
    assertEquals("From: Lainat line: 192", 1, lainat.etsiId(id1+1)); 
    assertEquals("From: Lainat line: 193", 2, lainat.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna241 
   * @throws SailoException when error
   */
  @Test
  public void testTallenna241() throws SailoException {    // Lainat: 241
    Lainat lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
    lainat = new Lainat(); 
    lainat.lueTiedostosta(); 
    lainat.tallenna(); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    assertEquals("From: Lainat line: 257", false, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    fbak.delete(); 
    assertEquals("From: Lainat line: 260", false, fbak.delete()); 
    assertEquals("From: Lainat line: 261", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa300 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa300() throws SailoException {    // Lainat: 300
    Lainat lainat = new Lainat(); 
    Laina eka = new Laina(1,1); 
    Laina toka = new Laina(2,2); 
    assertEquals("From: Lainat line: 305", 0, lainat.getLkm()); 
    lainat.lisaa(eka); assertEquals("From: Lainat line: 306", 1, lainat.getLkm()); 
    lainat.lisaa(toka); assertEquals("From: Lainat line: 307", 2, lainat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLainatIterator332 
   * @throws SailoException when error
   */
  @Test
  public void testLainatIterator332() throws SailoException {    // Lainat: 332
    Lainat lainat = new Lainat(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    laina1.rekisteroi(); laina2.rekisteroi(); 
    lainat.lisaa(laina1); 
    lainat.lisaa(laina2); 
    lainat.lisaa(laina1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Laina laina:lainat)
    ids.append(" "+laina.getLainaID()); 
    String tulos = " " + laina1.getLainaID() + " " + laina2.getLainaID() + " " + laina1.getLainaID(); 
    assertEquals("From: Lainat line: 350", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Laina>  i=lainat.iterator(); i.hasNext(); ) {
    Laina laina = i.next(); 
    ids.append(" "+laina.getLainaID()); 
    }
    assertEquals("From: Lainat line: 358", tulos, ids.toString()); 
    Iterator<Laina>  i=lainat.iterator(); 
    assertEquals("From: Lainat line: 361", true, i.next() == laina1); 
    assertEquals("From: Lainat line: 362", true, i.next() == laina2); 
    assertEquals("From: Lainat line: 363", true, i.next() == laina1); 
    try {
    i.next(); 
    fail("Lainat: 365 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}