package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.08 12:28:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UrheiluseurarekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa50 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa50() throws SailoException {    // Urheiluseurarekisteri: 50
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Jasen jouko1 = new Jasen(), jouko2 = new Jasen(); 
    assertEquals("From: Urheiluseurarekisteri line: 54", 0, rekisteri.getJasenia()); 
    rekisteri.lisaa(jouko1); assertEquals("From: Urheiluseurarekisteri line: 55", 1, rekisteri.getJasenia()); 
    rekisteri.lisaa(jouko2); assertEquals("From: Urheiluseurarekisteri line: 56", 2, rekisteri.getJasenia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa68 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa68() throws SailoException {    // Urheiluseurarekisteri: 68
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Valine pallo1 = new Valine(), pallo2 = new Valine(); 
    assertEquals("From: Urheiluseurarekisteri line: 72", 0, rekisteri.getValineita()); 
    rekisteri.lisaa(pallo1); assertEquals("From: Urheiluseurarekisteri line: 73", 1, rekisteri.getValineita()); 
    rekisteri.lisaa(pallo2); assertEquals("From: Urheiluseurarekisteri line: 74", 2, rekisteri.getValineita()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa86 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa86() throws SailoException {    // Urheiluseurarekisteri: 86
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    assertEquals("From: Urheiluseurarekisteri line: 90", 0, rekisteri.getLainoja()); 
    rekisteri.lisaa(laina1); assertEquals("From: Urheiluseurarekisteri line: 91", 1, rekisteri.getLainoja()); 
    rekisteri.lisaa(laina2); assertEquals("From: Urheiluseurarekisteri line: 92", 2, rekisteri.getLainoja()); 
  } // Generated by ComTest END
}