package seurarekisteri.test;
// Generated by ComTest BEGIN
import seurarekisteri.SailoException;
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.14 19:09:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UrheiluseurarekisteriTest {


  // Generated by ComTest BEGIN  // Urheiluseurarekisteri: 14
   private Urheiluseurarekisteri urheiluseurarekisteri; 
   private Jasen jasen1; 
   private Jasen jasen2; 
   private int jid1; 
   private int jid2; 

   public void alustaUrheiluseurarekisteri() {
     urheiluseurarekisteri = new Urheiluseurarekisteri(); 
     jasen1 = new Jasen(); jasen1.jasenenTaytto(); jasen1.rekisteroi(); 
     jasen2 = new Jasen(); jasen2.jasenenTaytto(); jasen2.rekisteroi(); 
     jid1 = jasen1.getJasenID(); 
     jid2 = jasen2.getJasenID(); 
     try {
     urheiluseurarekisteri.lisaa(jasen1); 
     urheiluseurarekisteri.lisaa(jasen2); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa99 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa99() throws SailoException {    // Urheiluseurarekisteri: 99
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Jasen jouko1 = new Jasen(), jouko2 = new Jasen(); 
    assertEquals("From: Urheiluseurarekisteri line: 103", 0, rekisteri.getJasenia()); 
    rekisteri.lisaa(jouko1); assertEquals("From: Urheiluseurarekisteri line: 104", 1, rekisteri.getJasenia()); 
    rekisteri.lisaa(jouko2); assertEquals("From: Urheiluseurarekisteri line: 105", 2, rekisteri.getJasenia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa128 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa128() throws SailoException {    // Urheiluseurarekisteri: 128
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Valine pallo1 = new Valine(), pallo2 = new Valine(); 
    assertEquals("From: Urheiluseurarekisteri line: 132", 0, rekisteri.getValineita()); 
    rekisteri.lisaa(pallo1); assertEquals("From: Urheiluseurarekisteri line: 133", 1, rekisteri.getValineita()); 
    rekisteri.lisaa(pallo2); assertEquals("From: Urheiluseurarekisteri line: 134", 2, rekisteri.getValineita()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa157 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa157() throws SailoException {    // Urheiluseurarekisteri: 157
    Urheiluseurarekisteri rekisteri = new Urheiluseurarekisteri(); 
    Laina laina1 = new Laina(1,1), laina2 = new Laina(2,2); 
    assertEquals("From: Urheiluseurarekisteri line: 161", 0, rekisteri.getLainoja()); 
    rekisteri.lisaa(laina1); assertEquals("From: Urheiluseurarekisteri line: 162", 1, rekisteri.getLainoja()); 
    rekisteri.lisaa(laina2); assertEquals("From: Urheiluseurarekisteri line: 163", 2, rekisteri.getLainoja()); 
  } // Generated by ComTest END
}