package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 15:43:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValineTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi27 */
  @Test
  public void testRekisteroi27() {    // Valine: 27
    Valine valine1 = new Valine(); 
    assertEquals("From: Valine line: 29", 0, valine1.getValineID()); 
    valine1.rekisteroi(); 
    Valine valine2 = new Valine(); 
    valine2.rekisteroi(); 
    int n1 = valine1.getValineID(); 
    int n2 = valine2.getValineID(); 
    assertEquals("From: Valine line: 35", n2-1, n1); 
  } // Generated by ComTest END
}