package seurarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import seurarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.14 11:39:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValineTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi29 */
  @Test
  public void testRekisteroi29() {    // Valine: 29
    Valine valine1 = new Valine(); 
    assertEquals("From: Valine line: 31", 0, valine1.getValineID()); 
    valine1.rekisteroi(); 
    Valine valine2 = new Valine(); 
    valine2.rekisteroi(); 
    int n1 = valine1.getValineID(); 
    int n2 = valine2.getValineID(); 
    assertEquals("From: Valine line: 37", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone51 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone51() throws CloneNotSupportedException {    // Valine: 51
    Valine valine = new Valine(); 
    valine.parse("   1  |  Sukset   | Fischer"); 
    Valine clone = valine.clone(); 
    assertEquals("From: Valine line: 56", valine.toString(), clone.toString()); 
    valine.parse("   4  |  Sauvat   | One Way"); 
    assertEquals("From: Valine line: 58", false, clone.toString().equals(valine.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta118 */
  @Test
  public void testAseta118() {    // Valine: 118
    Valine valine = new Valine(); 
    assertEquals("From: Valine line: 120", null, valine.aseta(1,"Sukset")); 
    assertEquals("From: Valine line: 121", "Hankintavuodessa on vain numeroita!", valine.aseta(3,"heppu")); 
    assertEquals("From: Valine line: 122", null, valine.aseta(3,"2018")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString171 */
  @Test
  public void testToString171() {    // Valine: 171
    Valine valine = new Valine(); 
    valine.parse("   1  |  Jalkapallo   | Select"); 
    assertEquals("From: Valine line: 174", true, valine.toString().startsWith("1|Jalkapallo|Select|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse193 */
  @Test
  public void testParse193() {    // Valine: 193
    Valine valine = new Valine(); 
    valine.parse("   1  |  Jalkapallo   | Select"); 
    assertEquals("From: Valine line: 196", 1, valine.getValineID()); 
    assertEquals("From: Valine line: 197", true, valine.toString().startsWith("1|Jalkapallo|Select|")); 
    valine.rekisteroi(); 
    int n = valine.getValineID(); 
    valine.parse(""+(n+22)); 
    valine.rekisteroi(); 
    assertEquals("From: Valine line: 203", n+22+1, valine.getValineID()); 
  } // Generated by ComTest END
}